### PR TITLE
Set fullProjectPath variable in entrypoint.sh

### LINKED ISSUE #255: fullProjectPath is not set when using runAsHostUser
**Bug description**

When setting `runAsHostUser` to true, the action gets the host user/group information using the `stat -c` command on `"$fullProjectPath"`, however, this fullProjectPath variable is never set. This results in the following error message: 
```
stat: cannot statx '': No such file or directory
Error: The process '/usr/bin/docker' failed with exit code 1
```
and then the action aborts.

**How to reproduce**

Start the unity-test-runner action on a self-hosted runner (running Ubuntu) with `runAsHostUser` set to true.

**Expected behavior**

I expect the action to run as host user (the full project path would need to be set) and not abort.

**Additional details**

The problem might also be a configuration problem on my side, but I believe the problem is in the [entrypoint.sh file](https://github.com/game-ci/unity-test-runner/blob/main/dist/platforms/ubuntu/entrypoint.sh), above line 16. I think the line where the fullProjectPath is being set is missing. (or at least I compared to the [entrypoint.sh of unity-builder](https://github.com/game-ci/unity-builder/blob/main/dist/platforms/ubuntu/entrypoint.sh), and there at line 14 the fullProjectPath variable is set, so I think this line is needed for the unity-test-runner as well. 
```
fullProjectPath="$GITHUB_WORKSPACE/$PROJECT_PATH"
```
I hope I described the issue sufficiently, if not I'd be happy to provide more details. Thank you for your help!

### PR DESCRIPTION
**Pull request by falko17**
#### Changes
This fixes the bug described in #255, i.e., it correctly sets the `fullProjectPath` variable in `entrypoint.sh` (the same way as it's done in https://github.com/game-ci/unity-builder).
This also adds a test that runs edit mode tests[^1] as the host user, which should hopefully catch issues like these.

[^1]: I have only done this for edit tests, as the type of test (or the platform) should not be affected by the choice to run this as the host user, and I did not want to double the number of tests.

#### Related Issues
- Fixes #255

#### Successful Workflow Run Link
- https://github.com/falko17/unity-test-runner/actions/runs/7317488746

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [X] ~~Docs (not applicable)~~
- [X] ~~Readme (not applicable)~~
- [X] Tests (added)

### CODE REVIEW

File: dist/platforms/ubuntu/entrypoint.sh [hunk 1]
```diff
@@ -3,12 +3,14 @@
 # Ensure machine ID is randomized for personal license activation
 if [[ "$UNITY_SERIAL" = F* ]]; then
   echo "Randomizing machine ID for personal license activation"
-  dbus-uuidgen > /etc/machine-id && mkdir -p /var/lib/dbus/ && ln -sf /etc/machine-id /var/lib/dbus/machine-id
```
Comment (webbertakken) [inline dist/platforms/ubuntu/entrypoint.sh:6]: This space was likely removed by mistake? It's now formatted differently from builder. Since we're using that as a reference let's not change this line here.

**Review by webbertakken — APPROVED** [review]

File: dist/platforms/ubuntu/entrypoint.sh (hunk 1 above)
Comment (falko17) [reply dist/platforms/ubuntu/entrypoint.sh:6]: Oh, my bad, this was indeed a mistake. I'll change it back.

Comment (falko17) [reply dist/platforms/ubuntu/entrypoint.sh]: Should be fixed now, thanks for the quick review!

**Review by AndrewKahr — APPROVED** [review]
